In [8]:
#dependencies
import pandas as pd
import plotly
import matplotlib.pyplot as plt
import plotly.plotly as py
import plotly.graph_objs as go
from scipy import stats
from numpy import arange,array,ones

In [9]:
plotly.tools.set_credentials_file(username = 'paolapoblete', api_key = 'AH15of7VDbJeKyPbfnpS')

In [10]:
#import and read CSVs

hotel_info_df = pd.read_csv(r'C:\Users\Paola\Documents\GitHub\ETL_team_5\csvs\hotel_info')
rental_rooms_df = pd.read_csv(r'C:\Users\Paola\Documents\GitHub\ETL_team_5\csvs\rental_rooms')
restaurants_df = pd.read_csv(r'C:\Users\Paola\Documents\GitHub\ETL_team_5\csvs\restaurant_ratings')

In [33]:
#check dataframes
hotel_info_df
#rental_rooms_df
#restaurants_df

    Unnamed: 0                                        hotel_names hotel_prices
0            0                        Holiday Inn Express Waikiki        C$227
1            1                                     Hotel La Croix        C$198
2            2                                The Modern Honolulu        C$313
3            3                     Outrigger Waikiki Beach Resort        C$328
4            4                                 Vive Hotel Waikiki        C$250
5            5                               Hilton Waikiki Beach        C$245
6            6                        Holiday Inn Express Waikiki        C$227
7            7                            Shoreline Hotel Waikiki        C$211
8            8           Hyatt Regency Waikiki Beach Resort & Spa        C$290
9            9                    ‘Alohilani Resort Waikiki Beach        C$322
10          10                                 Park Shore Waikiki        C$190
11          11                          Hyatt Place Waikiki Beach        C$232
12          12                              Coconut Waikiki Hotel        C$213
13          13                                         Aqua Oasis        C$185
14          14                        Hyatt Centric Waikiki Beach        C$264
15          15                Outrigger Reef Waikiki Beach Resort        C$264
16          16  Moana Surfrider, A Westin Resort & Spa, Waikik...        C$393
17          17                     The Surfjack Hotel & Swim Club        C$247
18          18        Embassy Suites by Hilton Waikiki Beach Walk        C$401
19          19                               Waikiki Resort Hotel        C$178
20          20                   Waikiki Beachcomber by Outrigger        C$290
21          21                                  Royal Grove Hotel        C$131
22          22                       Luana Waikiki Hotel & Suites        C$237
23          23                       Ilikai Hotel & Luxury Suites        C$321
24          24                  The New Otani Kaimana Beach Hotel        C$297
25          25                    Hilton Garden Inn Waikiki Beach        C$231
26          26                     Lotus Honolulu at Diamond Head        C$207
27          27                                   Sheraton Waikiki        C$573
28          28                          The Kahala Hotel & Resort        C$664
29          29                  Trump International Hotel Waikiki        C$528
30          30         The Ritz-Carlton Residences, Waikiki Beach        C$597

In [35]:
hotel_info_df['Average Price'] = [298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52, 298.52]
hotel_info_df

,Unnamed: 0,hotel_names,hotel_prices,Average Price
0,0,Holiday Inn Express Waikiki,C$227,298.52
1,1,Hotel La Croix,C$198,298.52
2,2,The Modern Honolulu,C$313,298.52
3,3,Outrigger Waikiki Beach Resort,C$328,298.52
4,4,Vive Hotel Waikiki,C$250,298.52
5,5,Hilton Waikiki Beach,C$245,298.52
6,6,Holiday Inn Express Waikiki,C$227,298.52
7,7,Shoreline Hotel Waikiki,C$211,298.52
8,8,Hyatt Regency Waikiki Beach Resort & Spa,C$290,298.52
9,9,‘Alohilani Resort Waikiki Beach,C$322,298.52
10,10,Park Shore Waikiki,C$190,298.52
11,11,Hyatt Place Waikiki Beach,C$232,298.52
12,12,Coconut Waikiki Hotel,C$213,298.52
13,13,Aqua Oasis,C$185,298.52
14,14,Hyatt Centric Waikiki Beach,C$264,298.52
15,15,Outrigger Reef Waikiki Beach Resort,C$264,298.52
16,16,"Moana Surfrider, A Westin Resort & Spa, Waikik...",C$393,298.52
17,17,The Surfjack Hotel & Swim Club,C$247,298.52
18,18,Embassy Suites by Hilton Waikiki Beach Walk,C$401,298.52
19,19,Waikiki Resort Hotel,C$178,298.52
20,20,Waikiki Beachcomber by Outrigger,C$290,298.52
21,21,Royal Grove Hotel,C$131,298.52
22,22,Luana Waikiki Hotel & Suites,C$237,298.52
23,23,Ilikai Hotel & Luxury Suites,C$321,298.52
24,24,The New Otani Kaimana Beach Hotel,C$297,298.52
25,25,Hilton Garden Inn Waikiki Beach,C$231,298.52
26,26,Lotus Honolulu at Diamond Head,C$207,298.52
27,27,Sheraton Waikiki,C$573,298.52
28,28,The Kahala Hotel & Resort,C$664,298.52
29,29,Trump International Hotel Waikiki,C$528,298.52
30,30,"The Ritz-Carlton Residences, Waikiki Beach",C$597,298.52

In [36]:
#average hotel prices

#traces
hotel_trace = go.Bar(
    x = hotel_info_df['hotel_names'],
    y = hotel_info_df['hotel_prices']
)

hard_line = go.Scatter(
    x = hotel_info_df['hotel_names'],
    y = hotel_info_df['Average Price']

)
data = [hotel_trace, hard_line]

#layout
layout = dict(title = 'Hotel Names by Prices',
              xaxis = dict(title = 'Hotels'),
              yaxis = dict(title = 'Prices'),
              autosize = True
             )

#figure
fig = dict(data = data, layout = layout)

#generates the graph and opens
py.iplot(fig)

In [26]:
#average hotel prices

#traces
hotel_trace = go.Bar(
    x = hotel_info_df['hotel_names'],
    y = hotel_info_df['hotel_prices']
)

hard_line = go.Scatter(
    x = hotel_info_df['hotel_names'],
    y = hotel_info_df['Unnamed: 0']

)
data = [hotel_trace, hard_line]

#layout
layout = dict(title = 'Hotel Names by Prices',
              xaxis = dict(title = 'Hotels'),
              yaxis = dict(title = 'Prices'),
              autosize = True
             )

#figure
fig = dict(data = data, layout = layout)

#generates the graph and opens
py.iplot(fig)

In [29]:
#average hotel prices

#traces
rental_trace = go.Bar(
    x = rental_rooms_df['Rental Room'],
    y = rental_rooms_df['Rental Price']
)

hard_line2 = go.Scatter(
    x = rental_rooms_df['Rental Room'],
    y = rental_rooms_df['Unnamed: 0']

)
data = [rental_trace, hard_line2]

#layout
layout = dict(title = 'Rental Rooms by Prices',
              xaxis = dict(title = 'Room Rentals'),
              yaxis = dict(title = 'Prices'),
              autosize = True
             )

#figure
fig2 = dict(data = data, layout = layout)

#generates the graph and opens
py.iplot(fig2)